apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ns-blogapp
  name: blogapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
