apiVersion: v1
kind: Service
metadata:
  namespace: ns-blogapp
  name: blogapp-service
spec:
  selector:
    app: blogapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30021
  type: NodePort
